const data = {
  products: [
    {
      _id: "1",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "2",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "3",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "4",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "5",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "1",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "2",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "3",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "4",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
    {
      _id: "5",
      name: "Rice",
      category: "Veg",
      image: "/images/p1.jpg",
      price: "$120",
      description: "Fresh foods",
    },
  ],
};

export default data;
